Bernoulli_t: -1
K: 5
K_plot: 40
NetworkStructure_1:
- -1
- 200
- 200
- 200
- 200
- 200
- 200
NetworkStructure_2:
- -1
- 500
- 80
Normal_t: -1
Uniform_t: 1
accelerator: null
accumulate_grad_batches: null
amp_backend: null
amp_level: null
augNearRate: 1000
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: null
batch_size: 512
benchmark: null
check_val_every_n_epoch: 1
computer: sky-Yongjie-xu
data_name: Olsson
data_path: ./data
dataname: Olsson
default_root_dir: null
detaalpha: 1.005
detect_anomaly: false
devices: null
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
epochs: 50000
eta: 1
explevel: 3
fast_dev_run: false
gpus: null
gradient_clip_algorithm: null
gradient_clip_val: null
inference_mode: true
ipus: null
knn: 5
l2alpha: 10
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
log_interval: 400
logger: true
lr: 0.001
max_epochs: null
max_steps: -1
max_time: null
method: Ours
metric: euclidean
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_components: 50
n_point: 60000000
name: digits_T
nu: 0.01
nu_rfa: 0.01
num_fea_aim: 2000
num_fea_per_pat: 80
num_latent_dim: 2
num_link_aim: 0.2
num_nodes: 1
num_pat: 8
num_processes: null
num_sanity_val_steps: 2
offline: 0
overfit_batches: 0.0
plugins: null
precision: 32
profiler: null
project_name: test
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_checkpoint: 0
seed: 1
showmainfig: 1
sigma: 1.0
strategy: null
sync_batchnorm: false
tpu_cores: null
track_grad_norm: -1
uselabel: 0
val_check_interval: null
